name: Update gist with WakaTime stats

on:
  schedule:
    - cron: "5 4 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@7c3b60d16e050e453b8bfe7ef484f171928a8726 # v5.0.0
        env:
          GIST_ID: ${{ secrets.WAKA_BOX_GIST_ID }}
          GH_TOKEN: ${{ secrets.WAKA_BOX_GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKA_BOX_WAKATIME_API_KEY }}
